services:
  satellite-temperatures:
    image: <see commit history for image name>
    ports: 
      - 1000:4000

  database:
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes:
     - db:/tmp/postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: my_db
        POSTGRES_USER: my_user
        POSTGRES_PASSWORD: my_password

volumes:
  db:
